---
- include: sudo.yml
- include: archiving.yml
- include: filesystems.yml
- include: building.yml
- include: packaging.yml
- include: idevice.yml
- include: scm.yml
- include: ssh.yml

- name: replace /etc/issue
  copy: src=issue.dark dest=/etc/issue owner=root group=root

- name: replace /etc/systemd/journald.conf
  copy: src=systemd/journald.conf dest=/etc/systemd/journald.conf owner=root group=root

- name: synchronize systemd services
  copy: src=systemd/system/ dest=/etc/systemd/system/ owner=root group=root
